### ISSUE TITLE
CoNLL2012 Datasets in .json format

### ISSUE THREAD

**Issue by MerrickWang1** [amazon-research/tanl#10]
datasets.py expects .json files for CoNLL2012 dataset. However, after searching online, I cannot find any preprocessing tools to yield .json files for the CoNLL2012 dataset.

Would the authors be able to provide a way to preprocess the CoNLL2012 dataset so that it can be used for training?

Thanks,

**Comment by MerrickWang1** [comment]
Could the authors provide a way to preprocess Conll12 for Coreference (conll12_coref)?

Thanks,

**Comment by 1826949** [comment]
Yes, I follow as well. Can instruction be provided?
