### ISSUE TITLE
ATIS and SNIPS Dataset Source

### ISSUE THREAD

**Issue by MerrickWang1** [amazon-research/tanl#11]
Hi,

Would you mind leaving some instructions for where you found/preprocessed the ATIS and SNIPS datasets? 

I found some .tsv files here for train/dev/test, but the format is not exactly what tanl/datasets.py expects. 

Thanks,

**Comment by niloofar17** [comment]
Hi @MerrickWang1 did you find any answer for this? I am trying to run the model on SNIPS in an episodic format but the code doesn't work for this case.

**Comment by MerrickWang1** [comment]
I was not able to find any answer for this - sorry.

**Comment by snowood1** [comment]
can't find it either.
