### ISSUE TITLE
Episode numbers in few-shot experiment

### ISSUE THREAD

**Issue by mtt1998** [amazon-research/tanl#3]
Hi,
      Thank you for sharing the code ! I'm trying to reproduce the results on FewRel 1.0 . And I'm wondering how many episodes and query numbers are used in 1 shot , and 5 shot cases, respectively ? 

Thanks.

**Comment by mtt1998** [comment]
Thank you for your help ! I can replicate the results with the sample config file . Did you ever try to evaluate with more episodes ? I suspect this will give a smaller performance variance .

**Comment by giove91** [comment]
You're welcome!
I don't think we tried, but you are right.
